name: Build Microsoft Office

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  # Snapcraft Token Valid till -
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Build it
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm install
        npm install -g electron-builder
        npm run dist
        electron-builder --linux snap --publish onTagOrDraft
    - uses: actions/upload-artifact@v2
      with:
        name: Linux
        path: |
          dist/Microsoft-Office-x86_64.AppImage
          dist/Microsoft-Office-amd64.deb
          dist/Microsoft-Office-amd64.snap
          dist/latest-linux.yml
    # - name: Install Snapcraft
    #   uses: samuelmeuli/action-snapcraft@v1.2.0
    #   with:
    #     snapcraft_token: ${{ secrets.SNAPCRAFT_TOKEN }}
    # - name: Use Snapcraft
    #   run: |
    #     snapcraft --help
    #     snapcraft upload --release=stable dist/Microsoft-Office-amd64.snap
  
  build-mac:
    name: macOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Prepare for app signing and notarization
      env:
        API_KEY: ${{ secrets.api_key }}
      if: ${{ env.API_KEY }}
      run: |
        echo "CSC_LINK=${{ secrets.mac_cert }}" >> $GITHUB_ENV
        echo "CSC_KEY_PASSWORD=${{ secrets.mac_cert_password }}" >> $GITHUB_ENV
        echo "APPLE_ID=${{ secrets.apple_id }}" >> $GITHUB_ENV
        echo "APPLE_ID_PASSWORD=${{ secrets.apple_id_password }}" >> $GITHUB_ENV
        echo "TEAM_ID=${{ secrets.team_id }}" >> $GITHUB_ENV
    - name: Build it
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm install
        npm run dist
    - uses: actions/upload-artifact@v2
      with:
        name: mac-binaries
        path: |
          dist/Microsoft-Office.dmg
          dist/Microsoft-Office.zip
          dist/latest-mac.yml
  build-windows:
    name: Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Build it
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm install
        npm run dist
    - uses: actions/upload-artifact@v2
      with:
        name: windows-binaries
        path: |
          dist/Microsoft-Office.exe
          dist/latest.yml